import {
  getEntity,
  getObjectByEntityAndId,
  getObjectsByEntityAndIds,
  getObjectsByEntityAndQuery,
  getArrayFromEntity,
  getArrayFromQuery,
  getIdsByEntityAndQuery,
  getIdsByEntityAndLastQuery,
  getMetaByEntityAndQuery,
  isFetching,
  isSchemaFetching,
  isIdFetching,
  getApiHost,
  getApiNetwork,
  getApiVersion,
  getApiNetworkDetails,
  getApiCacheDetails,
  getApiFeatured
} from './selectors'

export const selectors = {
  getEntity,
  getObjectByEntityAndId,
  getObjectsByEntityAndIds,
  getObjectsByEntityAndQuery,
  getArrayFromEntity,
  getArrayFromQuery,
  getIdsByEntityAndQuery,
  getIdsByEntityAndLastQuery,
  getMetaByEntityAndQuery,
  isFetching,
  isSchemaFetching,
  isIdFetching,
  getApiHost,
  getApiNetwork,
  getApiVersion,
  getApiNetworkDetails,
  getApiCacheDetails,
  getApiFeatured
}